# Generated by Django 5.1.1 on 2024-09-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_doctor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Specialization',
            new_name='specialization',
        ),
    ]
